# Makefile for procedural-gfx-fpga simulation

RTL = rtl/apu_pkg.sv rtl/gfx/apu_vga_timing.sv rtl/gfx/apu_cordic.sv rtl/gfx/apu_colorbars.sv rtl/gfx/apu_plasma.sv rtl/gfx/apu_top.sv
TB  = tb/sim_main.cpp
OUT = sim_apu_top

sim: $(RTL) $(TB)
	@mkdir -p sim
	verilator --cc --exe --build -Wall --top-module apu_top $(RTL) $(TB) -o $(OUT)
	./obj_dir/$(OUT)

sim_i2c: rtl/sys/i2c_controller.sv tb/sim_i2c.cpp
	@mkdir -p sim
	verilator --cc --exe --build -Wall --top-module i2c_controller rtl/sys/i2c_controller.sv tb/sim_i2c.cpp -o sim_i2c
	./obj_dir/sim_i2c

sim_config: rtl/sys/adv7513_config.sv rtl/sys/i2c_controller.sv tb/tb_adv7513_config.sv tb/sim_adv7513_config.cpp
	@mkdir -p sim
	verilator --cc --exe --build -Wall --top-module tb_adv7513_config tb/tb_adv7513_config.sv rtl/sys/adv7513_config.sv rtl/sys/i2c_controller.sv tb/sim_adv7513_config.cpp -o sim_adv7513_config
	./obj_dir/sim_adv7513_config

# Look check for the plasma scene: one frame to sim/plasma_frame.ppm for
# eyeballing against anim/render.py's output. SCENE is overridden only here;
# the board build picks PLASMA in de10nano_top and the default sim stays
# colorbars, so no regression path depends on this target's result.
sim_plasma: $(RTL) tb/sim_plasma.cpp
	@mkdir -p sim
	verilator --cc --exe --build -Wall --top-module apu_top -GSCENE=1 $(RTL) tb/sim_plasma.cpp -o sim_plasma
	./obj_dir/sim_plasma

# Randomized-reset tier: kills reliance on zero-init state machines. Verilator
# stays 2-state; this is a seed sweep, not X-propagation. 5 seeds green on
# sim, plasma and cordic harnesses, measured 2026-09-28.
XSEEDS = 1 2 3 4 5

xprop: $(RTL) tb/sim_main.cpp
	@mkdir -p sim
	verilator --cc --exe --build -Wall --top-module apu_top --x-initial unique --x-assign unique $(RTL) tb/sim_main.cpp -o sim_xprop
	@for s in $(XSEEDS); do ./obj_dir/sim_xprop +verilator+rand+reset+2 +verilator+seed+$$s > /dev/null || { echo "xprop: FAIL seed $$s"; exit 1; }; done
	@echo "xprop: all seeds green"

# sim/cordic_golden.hex is generated from the model, so a stale file can never
# cross-check the RTL: make rebuilds it whenever cordic_golden.py changes.
# The pinned sha256 catches environment drift: a python or libm that would
# emit a different table fails here instead of silently re-baselining.
sim/cordic_golden.hex: tb/cordic_golden.py tb/cordic_golden.sha256
	@mkdir -p sim
	python3 tb/cordic_golden.py emit sim/cordic_golden.hex
	shasum -a 256 -c tb/cordic_golden.sha256

sim_cordic: rtl/gfx/apu_cordic.sv tb/sim_cordic.cpp sim/cordic_golden.hex
	verilator --cc --exe --build -Wall --top-module apu_cordic rtl/gfx/apu_cordic.sv tb/sim_cordic.cpp -o sim_cordic
	./obj_dir/sim_cordic

# M1 cosim harness (contract 4b/4c). Red by design against the ports-only
# stub until the real core lands: kept out of regress and coverage on
# purpose, wired in when green. -GPOR_CYCLES=8 follows the -GSCENE
# override precedent; the golden files are regenerated by
# tools/rv32sweep.py.
sim_cpu: rtl/cpu/rv32_core.sv tb/sim_cpu.cpp
	verilator --cc --exe --build -Wall --top-module rv32_core -GPOR_CYCLES=8 rtl/cpu/rv32_core.sv tb/sim_cpu.cpp -o sim_cpu
	./obj_dir/sim_cpu tools/golden/hart0.hex tools/golden/hart0.trace.csv tools/golden/hart0.state.txt tools/golden/hart0.ram.bin

# Lint only (no C++ build)
lint: $(RTL)
	verilator --lint-only -Wall --top-module apu_top $(RTL)

lint_i2c: rtl/sys/i2c_controller.sv
	verilator --lint-only -Wall rtl/sys/i2c_controller.sv

lint_top: rtl/apu_pkg.sv rtl/gfx/apu_vga_timing.sv rtl/gfx/apu_cordic.sv rtl/gfx/apu_colorbars.sv rtl/gfx/apu_plasma.sv rtl/gfx/apu_top.sv rtl/sys/i2c_controller.sv rtl/sys/adv7513_config.sv rtl/sys/pll_25m.sv rtl/sys/de10nano_top.sv
	verilator --lint-only -Wall --top-module de10nano_top rtl/apu_pkg.sv rtl/gfx/apu_vga_timing.sv rtl/gfx/apu_cordic.sv rtl/gfx/apu_colorbars.sv rtl/gfx/apu_plasma.sv rtl/gfx/apu_top.sv rtl/sys/i2c_controller.sv rtl/sys/adv7513_config.sv rtl/sys/pll_25m.sv rtl/sys/de10nano_top.sv rtl/sys/sync_reset.sv

# apu_cordic gets its own lint as a fast standalone check; lint_top covers
# it in-tree (instantiated via apu_plasma under apu_top).
lint_cordic: rtl/gfx/apu_cordic.sv
	verilator --lint-only -Wall --top-module apu_cordic rtl/gfx/apu_cordic.sv

golden:
	python3 tb/cordic_golden.py

tools-tests:
	python3 tools/tests/test_rv32asm.py
	python3 tools/tests/test_rv32enc.py
	python3 tools/tests/test_rv32iss.py

# Serial on purpose: every Verilator target builds into obj_dir, and
# $(MAKE) -j1 defeats an inherited -j from `make -j8 regress`.
GATES = lint lint_top lint_cordic lint_i2c sim sim_i2c sim_config golden sim_cordic sim_plasma tools-tests

regress:
	@for t in $(GATES); do printf "== %s\n" $$t; $(MAKE) -j1 $$t || exit 1; done
	@echo "regress: all gates green"

# Coverage tier: build every harness with --coverage into obj_dir (the same
# dir the sim targets use; a nested --Mdir breaks the harness path on the CI
# Verilator, which does not rewrite it relative to Mdir), run each, move its
# dat, merge, enforce floors. Serial: each build replaces obj_dir before its
# run, so interleaving build/run/mv per target is safe.
# Floors are baseline minus margin (B10 convention): measured 2026-09-29 and
# recorded in docs/verification.md. Tighten with a new measurement, never
# loosen without one.
COV_LINE_FLOOR = 85
COV_TOGGLE_FLOOR = 84

coverage: sim/cordic_golden.hex
	@mkdir -p sim/cov
	verilator --cc --exe --build -Wall --coverage --top-module apu_top $(RTL) tb/sim_main.cpp -o sim_cov_apu
	./obj_dir/sim_cov_apu
	mv sim/coverage.dat sim/cov/apu.dat
	verilator --cc --exe --build -Wall --coverage --top-module apu_top -GSCENE=1 $(RTL) tb/sim_plasma.cpp -o sim_cov_plasma
	./obj_dir/sim_cov_plasma
	mv sim/coverage.dat sim/cov/plasma.dat
	verilator --cc --exe --build -Wall --coverage --top-module i2c_controller rtl/sys/i2c_controller.sv tb/sim_i2c.cpp -o sim_cov_i2c
	./obj_dir/sim_cov_i2c
	mv sim/coverage.dat sim/cov/i2c.dat
	verilator --cc --exe --build -Wall --coverage --top-module tb_adv7513_config tb/tb_adv7513_config.sv rtl/sys/adv7513_config.sv rtl/sys/i2c_controller.sv tb/sim_adv7513_config.cpp -o sim_cov_config
	./obj_dir/sim_cov_config
	mv sim/coverage.dat sim/cov/config.dat
	verilator --cc --exe --build -Wall --coverage --top-module apu_cordic rtl/gfx/apu_cordic.sv tb/sim_cordic.cpp -o sim_cov_cordic
	./obj_dir/sim_cov_cordic
	mv sim/coverage.dat sim/cov/cordic.dat
	verilator_coverage --write sim/cov/merged.dat sim/cov/apu.dat sim/cov/plasma.dat sim/cov/i2c.dat sim/cov/config.dat sim/cov/cordic.dat
	verilator_coverage sim/cov/merged.dat | tee sim/cov/summary.txt
	@python3 -c "import re, sys, collections; recs = [(re.search(r'(line|toggle|branch|expr|user|fsm_state|fsm_arc)', l).group(1), int(l.rsplit(None, 1)[1])) for l in open('sim/cov/merged.dat', errors='replace') if l.startswith('C ')]; print('merged.dat head: ' + repr(open('sim/cov/merged.dat', errors='replace').read()[:300])) if not recs else None; tot = collections.Counter(t for t, _ in recs); cov = collections.Counter(t for t, c in recs if c); pct = {k: 100.0 * cov[k] / tot[k] for k in tot}; line, toggle = pct.get('line', 0.0), pct.get('toggle', 0.0); fl, ft = int(sys.argv[1]), int(sys.argv[2]); print('merged.dat: ' + ', '.join(k + ' ' + format(pct[k], '.1f') + '%' for k in sorted(pct))); print('floors: line >= ' + str(fl) + ', toggle >= ' + str(ft) + '; measured line ' + format(line, '.1f') + ', toggle ' + format(toggle, '.1f')); sys.exit(0 if line >= fl and toggle >= ft else 1)" $(COV_LINE_FLOOR) $(COV_TOGGLE_FLOOR)

# Clean up build artifacts
clean:
	rm -rf obj_dir
	rm -f sim/*.ppm
	rm -f sim/cordic_golden.hex

# sim/ and obj_dir/ are real directories, so the run targets must be phony
# or make treats them as up to date on a rerun
.PHONY: sim sim_plasma sim_i2c sim_config sim_cordic sim_cpu lint lint_i2c lint_top lint_cordic regress tools-tests golden xprop coverage clean